spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/simple-api-practice
    password: Eliaro-14.
  application:
    name: simple-api-practice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to my application!
server:
  port: '8083'
