server:
  port: 8084

spring:
  profiles:
    active: prod

---

spring:
  profile: dev
  application:
    name: springboot-practice-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Eliaro-14.
    url: jdbc:mysql://localhost:3306/springboot_practice_app
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hey techies, am just having fun with Springboot:)

---

spring:
  profile: prod
  application:
    name: springboot-practice-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Eliaro-14.
    url: jdbc:mysql://localhost:3306/springboot_practice_app-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hey techies, am just having fun with Springboot:)

---

spring:
  profile: qa
  application:
    name: springboot-practice-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Eliaro-14.
    url: jdbc:mysql://localhost:3306/springboot_practice_app-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hey techies, am just having fun with Springboot:)