server:
  port: 8081

spring:
  profiles:
    active: qa

---

spring:
  profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/apartment-management
    username: root
    password: Eliaro-14.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to my Apartment Management app!

---

spring:
  profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/apartment-management-prod
    username: root
    password: Eliaro-14.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to my Apartment Management app!

---

spring:
  profile: qa
  datasource:
    url: jdbc:mysql://localhost:3306/apartment-management-qa
    username: root
    password: Eliaro-14.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to my Apartment Management app!
