server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apartment-management
    username: root
    password: Eliaro-14.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to my Apartment Management app!